function appStart(){if(ctx=(canvas=document.querySelector("canvas")).getContext("2d"),loadImages(),localStorage.highscore&&(highscore=localStorage.highscore,scoreDisplay[0].innerText=`High Score: ${highscore}`),localStorage.mute){if("Mute"===(mute=localStorage.mute))return gamemusic.play();gamemusic.pause(),footer.innerHTML=`
            <div id="softleft">${mute}</div>
            <div id="softright">Tutorial</div>
        `}}function ad(e){window.navigator.onLine&&ableToShowAD&&(loadingAd.style.display="block",ingame&&pause(),getKaiAd({publisher:" fe2d9134-74be-48d8-83b9-96f6d803efef",app:"Falling Numbers",onerror(e){loadingAd.style.display="none",alert("An error occurred while attempting to serve an ad"),clearTimeout(adCapCounter),ableToShowAD=!1,adCapCounter=setTimeout(()=>{ableToShowAD=!0},3e4),gameOver(),console.log("KaiAd Error:",e)},onready(i){clearTimeout(adCapCounter),ableToShowAD=!1,adCapCounter=setTimeout(()=>{ableToShowAD=!0},3e4),i.call("display"),loadingAd.style.display="none",i.on("display",()=>{ingame&&pause()}),i.on("click",()=>{e&&(clickedOnAd=!0)}),i.on("close",()=>{clickedOnAd?(clickedOnAd=!1,respawn()):e&&(alert("You wonder why you didn't respawn?\nYou have to open the ad to respawn."),respawnScreen.style.display="none",gameScreen.style.display="block")})}}))}function loadImages(){background.src="img/game/background.png",player.img.src=player.src}function draw(){ctx.drawImage(background,0,0,300,250),ctx.drawImage(player.img,player.x,player.y,player.width,player.height),fallingNumbers.forEach(e=>{ctx.drawImage(e.img,e.x,e.y,e.width,e.height)}),requestAnimationFrame(draw)}function startGame(){fallingNumbers=[],player.x=145,player.num=0,player.src="img/game/0.png",player.img.src=player.src,footer.innerHTML='<div id="softleft">Pause</div>',startScreen.style.display=gameOverScreen.style.display=credits.style.display="none",scoreDisplay[0].innerText="Score: 0",scoreDisplay[0].style.display="block",ingame=!0,draw(),newNumbers=setInterval(addNewNumber,100),updateInterval=setInterval(update,25)}function dead(){if(left=right=ingame=!1,clearInterval(newNumbers),clearInterval(updateInterval),gameOverScreen.style.display="block",scoreDisplay[0].style.display="none",footer.innerHTML=`
        <div id="softleft">Tutorial</div>
        <div id="softright">Home</div>
        `,!alreadyRespawned&&window.navigator.onLine&&ableToShowAD){progressbar.classList.add("animate"),scoreDisplay[1].innerText=`Score: ${score}`,gameScreen.style.display="none",respawnScreen.style.display="block",gameOverScreenTimeout=setTimeout(gameOver,5300);return}}function respawnAd(){clearTimeout(gameOverScreenTimeout),progressbar.style.animationPlayState="paused",ad(!0)}function respawn(){gameOverScreen.style.display="none",progressbar.classList.remove("animate"),progressbar.style.animationPlayState="running",respawnScreen.style.display=scoreDisplay[0].style.display="block",ingame=alreadyRespawned=!0,fallingNumbers.forEach(e=>{e.y-=100}),footer.innerHTML='<div id="softleft">Pause</div>',newNumbers=setInterval(addNewNumber,100),updateInterval=setInterval(update,25)}function gameOver(){if(spawnIntervalTime=1800,respawnScreen.style.display="none",gameScreen.style.display="block",timeGone=0,alreadyRespawned=!1,progressbar.classList.remove("animate"),progressbar.style.animationPlayState="running",isNewHighScore(),1==++deathCount)return ad(),deathCount=0;4==deathCount&&(ad(),deathCount=0)}function restart(){fallingNumbers=[],pauseScreen.style.display="none",spawnIntervalTime=1800,timeGone=score=0,left=right=paused=!1,footer.innerHTML=`
        <div id="softleft">Pause</div>
    `,player.x=145,player.num=0,player.src="img/game/0.png",player.img.src=player.src,scoreDisplay[0].innerText=`Score: ${score}`}function pause(){paused=!0,pauseScreen.style.display="block",footer.innerHTML=`
        <div id="softleft">Restart</div>
        <div id="softright">Home</div>
    `}function tutorial(){startScreen.style.display=gameOverScreen.style.display=scoreDisplay[0].style.display=credits.style.display="none",tutorialScreen.style.display="block",footer.innerHTML=`
        <div id="softleft" style="color: #444">Last</div>
        <div style="font-size: 25px;font-weight: 700; position: absolute; left: 50%; transform: translate(-50%, -50%)">SKIP</div>
        <div id="softright">Next</div>
    `}function handleTutorialText(e){return"left"===e?tutorialText.innerText.includes("5")?void 0:tutorialText.innerText.includes("4")?(footer.children[0].style.color="#444",tutorialText.innerText="Press Enter/5 to increase the player's number."):tutorialText.innerText.includes("6")?tutorialText.innerText="Press Left/4 to move left.":tutorialText.innerText.includes("Match")?(footer.children[2].innerText="Next",tutorialText.innerText="Press Right/6 to move right."):void 0:tutorialText.innerText.includes("5")?(footer.children[0].style.color="#000",tutorialText.innerHTML="Press Left/4 to move left."):tutorialText.innerText.includes("4")?tutorialText.innerText="Press Right/6 to move right.":tutorialText.innerText.includes("6")?(footer.children[2].innerText="Finish",tutorialText.innerText="Match the player's number to the falling number and collect it to score points."):tutorialText.innerText.includes("Match")?endTutorial():void 0}function endTutorial(){if(tutorialText.innerText="Press Enter/5 to increase the player's number.",onGameOverScreen){tutorialScreen.style.display="none",gameOverScreen.style.display="block",footer.innerHTML=`
            <div id="softleft">Tutorial</div>
            <div id="softright">Home</div>
        `,onGameOverScreen=!1;return}home()}function home(){gameOverScreen.style.display=pauseScreen.style.display=tutorialScreen.style.display=creditsScreen.style.display="none",scoreDisplay[0].style.display=startScreen.style.display=credits.style.display="block",scoreDisplay[0].innerText=`High Score: ${highscore}`,fallingNumbers=[],player.x=3e3,clearInterval(newNumbers),clearInterval(updateInterval),footer.innerHTML=`
        <div id="softleft">${mute}</div>
        <div id="softright">Tutorial</div>
    `,paused=ingame=!1}function isNewHighScore(){if(score>highscore){localStorage.highscore=highscore=score,scoreDisplay[2].innerHTML=`New High Score!<br>Score: ${score}`,score=0;return}scoreDisplay[2].innerText=`Score: ${score}`,score=0}function update(){if(paused)return;let e=0;e=score/600>.96?score/700:score/550,left&&player.x>3&&(player.x-=2.95+e),right&&player.x+player.width<=297&&(player.x+=2.95+e),fallingNumbers.forEach(e=>{if(e.y+=e.speed,e.x+e.width>player.x&&e.y+e.height>player.y&&e.x<player.x+player.width&&e.y<player.y+player.height){if(player.num===e.num){fallingNumbers=fallingNumbers.filter(i=>i!=e),score+=e.num+1,scoreDisplay[0].innerText=`Score: ${score}`,spawnIntervalTime>=850&&(spawnIntervalTime=1800-score/.2);return}return dead(),hitNumber=e}e.y>130&&(fallingNumbers=fallingNumbers.filter(i=>i!=e))})}function increasePlayerNumber(){9!==player.num?player.num++:player.num=0,player.img.src="img/game/"+player.num+".png"}function addNewNumber(){if(paused)return;if(!(spawnIntervalTime-timeGone<=0))return timeGone+=100;timeGone=0,number=parseInt(10*Math.random()),speed=score/300>1.05?score/500:score/300;let e={num:number,x:260*Math.random(),y:-30*Math.random(),height:17,width:33,src:"img/game/"+number+".png",img:new Image,speed:.9+speed};(chance=Math.random())>=.6-score/900&&(e.speed+=.38*Math.random()),e.img.src=e.src,fallingNumbers.push(e)}function un$mute(){if(gamemusic.paused){gamemusic.play(),mute="Mute",footer.innerHTML=`
            <div id="softleft">${mute}</div>
            <div id="softright">Tutorial</div>
        `,localStorage.mute=mute;return}gamemusic.pause(),localStorage.mute=mute="Unmute",footer.innerHTML=`
        <div id="softleft">${mute}</div>
        <div id="softright">Tutorial</div>
    `}